spring.datasource.url=jdbc:postgresql://aws-1-us-west-2.pooler.supabase.com:5432/postgres?user=postgres.ayopexicdgvmnwaimdll&password=HtVJYpikJtZyp5kw
spring.datasource.username=postgres.ayopexicdgvmnwaimdll
spring.datasource.password=HtVJYpikJtZyp5kw